In [ ]:
import numpy as np
arr=np.array([1,2,3])
print("number of dimensional:",arr.ndim)
print("size of array :",arr.size)
print("data type:",arr.dtype)
print("shape of array:",arr.shape)
print("item size",arr.itemsize)
arr1=np.array([[1,2,3],[2,3,4]])
print("number of dimensional:",arr1.ndim)
print("size of array :",arr1.size)
print("data type:",arr1.dtype)
print("shape of array:",arr1.shape)
print("item size",arr1.itemsize)
arr2=np.array([[[1,2,3],
               [1,2,3],
               [4,5,6]]])

print("number of dimensional:",arr2.ndim)
print("size of array :",arr2.size)
print("data type:",arr2.dtype)
print("shape of array:",arr2.shape)
print("item size",arr2.itemsize)

number of dimensional: 1
size of array : 3
data type: int64
shape of array: (3,)
item size 8
number of dimensional: 2
size of array : 6
data type: int64
shape of array: (2, 3)
item size 8
number of dimensional: 3
size of array : 9
data type: int64
shape of array: (1, 3, 3)
item size 8


In [ ]:
np.random.seed(5)
np.random.randint(0,500,size=(5,5))

array([[355, 206, 495, 189, 486],
       [118, 400,  73,   8, 228],
       [231, 446, 411, 112, 158],
       [208,   7, 204, 399, 113],
       [437, 487,  80,  27,  44]])

In [ ]:
arr1 = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [1, 4, 3, 5]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24],
                 [9, 7, 6, 5]],

                [[4, 5, 6, 7],
                 [54, 65, 34, 23],
                 [34, 43, 54, 32],
                 [76, 312, 34, 12]]])


print("Shape of the array:", arr1.shape)

Shape of the array: (3, 4, 4)


In [ ]:
arr5=np.array([[1,2],[3,2]])
arr6=np.array([[2,3]])
u=np.concatenate((arr5,arr6))
print(u)

[[1 2]
 [3 2]
 [2 3]]


In [ ]:
arr5=np.array([[1,2,3,2]])
arr6=np.array([[4,2,3,9]])
u=np.stack((arr5,arr6))
print(u)

[[[1 2 3 2]]

 [[4 2 3 9]]]


In [ ]:
arr5=np.array([[1,2,3,2]])
arr6=np.array([[4,2,3,9]])
u=np.vstack((arr5,arr6))
print(u)

[[1 2 3 2]
 [4 2 3 9]]


In [ ]:
arr5=np.array([[1,2,3,2]])
arr6=np.array([[4,2,3,9]])
u=np.hstack((arr5,arr6))
print(u)

[[1 2 3 2 4 2 3 9]]


In [ ]:

arr8=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
arr4=np.hsplit(arr8,3)

[array([[[1, 2, 3]]]), array([[[3, 4, 5]]]), array([[[6, 7, 8]]])]

In [ ]:
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[1,1]

5

In [ ]:
array[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
import numpy as np
x=np.array([[1,2],[2,4],[6,4]])
c=np.ones_like(x)
c

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
import numpy as np
x=np.array([[1,2],[2,4],[6,4]])
c=np.zeros_like(x)
c

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
import numpy as np

c=np.eye(3,k=0)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
arr0=np.arange(0,5,1)
print("the array element",arr0)
sub=arr0[[0,2]]
print("arr element by index",sub)

the array element [0 1 2 3 4]
arr element by index [0 2]
